//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarJudgement
    {
        public Nullable<int> CarId { get; set; }
        public Nullable<int> OverAllExterior { get; set; }
        public Nullable<int> FitNFinishExterior { get; set; }
        public Nullable<int> UniquenessOfProductExterior { get; set; }
        public Nullable<int> OneOfCustomizationsExterior { get; set; }
        public Nullable<int> PaintCleanlinessExterior { get; set; }
        public Nullable<int> PaintApperanceExterior { get; set; }
        public Nullable<int> PaintCompletenessExterior { get; set; }
        public Nullable<int> PaintOriginalityExterior { get; set; }
        public Nullable<int> CleanlinessEngine { get; set; }
        public Nullable<int> ModificationsEngine { get; set; }
        public Nullable<int> AccessoriesEngine { get; set; }
        public Nullable<int> UniquenessOfProductsEngine { get; set; }
        public Nullable<int> OneOfCustomizationsEngine { get; set; }
        public Nullable<int> CleanlinessUCDetails { get; set; }
        public Nullable<int> PaintOrPowercoatUCDetails { get; set; }
        public Nullable<int> BreaksUCPerformance { get; set; }
        public Nullable<int> SuspensionUCPerformance { get; set; }
        public Nullable<int> CleanlinessWheels { get; set; }
        public Nullable<int> AppearanceWheels { get; set; }
        public Nullable<int> UniquenessOfProductsWheels { get; set; }
        public Nullable<int> OverallTiers { get; set; }
        public Nullable<int> CleanlinessInterior { get; set; }
        public Nullable<int> AccessoriesInterior { get; set; }
        public Nullable<int> UpholsteryInterior { get; set; }
        public Nullable<int> UniquenessOfProductsInterior { get; set; }
        public Nullable<int> SoundICEDetails { get; set; }
        public Nullable<int> ICEICEDetails { get; set; }
        public Nullable<int> UniquenessOfProductsICEDetails { get; set; }
        public Nullable<int> QualityOfInstallICEDetails { get; set; }
        public Nullable<int> UniquenessOfInstallation { get; set; }
        public Nullable<int> OverallAppearanceODetails { get; set; }
        public Nullable<int> DisplayODetails { get; set; }
        public string JudgedByJudgedDetails { get; set; }
        public Nullable<System.DateTime> JudgedDateJudgedDetails { get; set; }
        public int CarJudgementID { get; set; }
    }
}
