//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarShow
    {
        public CarShow()
        {
            this.CarShowCarModels = new HashSet<CarShowCarModel>();
        }
    
        public int CarShowID { get; set; }
        public string CarShowName { get; set; }
        public string CarShowDescription { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual ICollection<CarShowCarModel> CarShowCarModels { get; set; }
    }
}
