//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarShowCarModel
    {
        public int CarShowCarModelID { get; set; }
        public int CarShowID { get; set; }
        public int CarModelID { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CarShow CarShow { get; set; }
    }
}
